### PR TITLE
Full blockland v20 opcodes added

### PR DESCRIPTION
**Pull request by SieniWAT**
Hello,
I added most opcodes for v20.

The decompile is successful, and i am able to get in game.

### CODE REVIEW

**Comment by rndtrash** [comment]
Hi, thank you so much for finishing it! I was stuck because of the opcodes 0x50 and 0x20 that mangled the result, and looking at the opcode table I guess I made a lot of wrong assumptions based on the Ghidra output, I'm not that good at it :/

If you don't mind, can you please tell me how did you get these opcodes right? I'm still learning all this reverse engineering stuff.

Anyway, LGTM!

**Comment by SieniWAT** [comment]
Hello,
My approach to finding the opcodes was more brute force than anything, i would take a dso identical between v21 and v20 and I would look at patterns of opcodes to make a kind of educated guess as to which is which. I didn't even think about using something like ghidra for this, but i would actually be really interested to hear what the workflow was for this.

**Comment by rndtrash** [comment]
That's actually a really clever solution; you were thinking outside the box! I didn't think of it at all because I'm not a part of the community, and I was so focused on v20 that I didn't even think about checking out the next versions of the game. Oh, well.

My workflow is not anything special. First, I tried to find a big ol' switch case based on my previous experience of making byte code machines. Then I made some attempts at trying to figure out what does what, but then I remembered that Torque3D became open source a long time ago [(11 years ago, damn!)](https://github.com/GarageGames/Torque3D/tree/v1), so I checked out one of the first commits and I found almost exactly the same function: `CodeBlock::exec`. Of course, the byte code version of that one was way never than v20, but many things were the same, including everything that used string, float, and int stacks, bitwise operations, jumps, and whatnot. Though it was still hard to match everything 1-to-1 since Ghidra's C code generation was suboptimal, to say the least, there were a lot of unnecessary GOTOs. I can send you my Ghidra project if you want.

**Comment by SieniWAT** [comment]
Ah, i see. It's wise, and definitely beyond what i would have initially thought of :p

**Comment by rndtrash** [comment]
Thank you for your kind words! :)

While you're here, I'd like to get your opinion on the mainstreaming of this code. Do you think it's worth the effort? Having a switch for choosing between v20 and v21 bytecode would be nice, but I don't think Electrk will merge the PR; after all, the last update of dso.js was three years ago.

**Comment by SieniWAT** [comment]
Sadly, i believe dso.js is going to be obsoleted, eventually.
Electrk has been working on something called dso sharp mentioned on their website https://electrk.rocks/, but it's yet to come out, and i don't know about its status, but i think i have heard of it being used in context with v20, in fact this was part of the reason I wanted to add v20 support to dso.js in the meantime.

**Comment by rndtrash** [comment]
Understandable. Well, I'm looking forward to the updates on DSO Sharp. Thank you, and good luck!

**Comment by SieniWAT** [comment]
Hi!
It's been quite a long time, but I recently came back to this project after having some Blockland reverse engineering thoughts in mind. I'm coming here to let you know about a few things:

1. It looks like DSO Sharp was "released" in an unfinished state and Elletra began work on a rewrite of dso.js. 

2. I've got my eyes on potentially figuring out a list of opcodes for other important blockland versions, notably it seems like the community is interested in v1. The recently archived Blockland retail beta is also probably of note, but it uses the same opcodes as a base Torque 1.3 game, so those opcodes are already out there and just need to be put into a good decompiler.
 
3. Frankly, I'm still a novice at reverse engineering, but I think I'd like to extend my efforts to creating a public reversal of Blockland's engine-specific functions and classes (e.g. fxDTSBrick, the oct tree, batcher, and more). This was done and released as Blockland Rebuilt, but they aren't going forwards to release any of the _extremely valuable_ Torque engine knowledge. I thought you'd like to hear about this, I believe it may be something you're interested in :)
If you are, let me know!

**Comment by rndtrash** [comment]
Oh, hey, it's nice to see you again!

So far, it sounds really interesting. I think you might need to know that I don't participate in the community, so I'm not sure about the recent developments. This project started as a challenge by a friend; the only piece of context I got is that there is *someone* who is holding the source code of a niche game, and that niche game turned out to be a game from my childhood, so I took the challenge.

Now I'd like to help you out with this one, but I have a couple of questions. First, should we wait for the rewrite to be done? I can see the last commit being only a week old, and main.ts consists only of a single console.log :^)

And second, is upstreaming of the v20 opcode changes still not being considered? And what about the other versions, such as the new old v1? Do we have to keep going as a fork?

But so far, count me in! :D

Cheers!

**Comment by SieniWAT** [comment]
Wrong account. Sorry O_O
Anyways,

Hi! I don't necessarily participate in the community either, rather, I'm just a lurker. It's a game from my childhood as well and having the privilege to be able to explore it and understand how it works on a technological level has been a dream of mine since I was just discovering reverse engineering when I was like 13, haha. 

On the other hand, I'm not particularly sure what's going on over at Elletra's side of things, I'm not really in that circle. I'm sure the v20 opcodes are known, decompiled scripts have been being privately shared for a while now, so it's probably just "on the plate" or just rather forgotten in a public release at least, since I know the project is a little old and was probably initially meant for just that one scope.

I don't think it hurts to at least determine the opcodes for v1 while waiting for some progress. They never change, so it certainly won't hurt if the rewrite takes a while, but it has the potential to be useful in the future.

In fact, I've already gotten a decent bit through v1's opcodes just in the past night with just 2 scripts left. I'm having some errors that can probably be attributed to me, but otherwise I'm applying my good old technique of compare and test. Such a thing can probably be automated, but I'm lazy!

If you have somewhere we can DM, let me know!

**Comment by rndtrash** [comment]
Sure, DM me on Discord: `shlakoblock`

I can make a Matrix account or something like that if you're into privacy, but I prefer Discord.

**Pull request merged**
